### ISSUE TITLE
Leaderboards stopped working properly in already released stand-alone game. Still work ok when running in Unity Editor

### ISSUE THREAD

**Issue by SergioDelValle** [Facepunch/Facepunch.Steamworks#148]
I've published a game back in january with facepunch.steamworks integration. Everything was working ok, with leaderboards integration, uploading scores, etc.

Suddenly leaderboards don't work. If i'm running the same version of the game in Unity's Editor everything is fine, but the already published game doesn't connect to them.

I have not updated the release since january so I'm pretty sure it's nothing on my side since it was already working. Maybe something is different in leaderboards and facepunch isn't supporting it yet?

I've uploaded a debug version of my game and when I check my leaderboard and "leaderboard.isError" returns true every time. I'm checking the leaderboard with 
`leaderboard= Client.Instance.GetLeaderboard("NormalRanking", Client.LeaderboardSortMethod.Descending, Client.LeaderboardDisplayType.Numeric);`

All other functionality such as getting usernames and avatar works without problems.

Really worried about this :S

**Comment by yyr57695** [comment]
I published Super Multitasking on Steam back in February and I now see that my leaderboards are broken too.  Stats and other functionality work.  
This isn't good.  Please address this or I'll be forced to drop what I'm doing and instead integrate a different library for leaderboard support =(

**Comment by alevastor** [comment]
Have the same problem. Actually it seems to be fixed, when building for 64 bit system with usage of steam_api64.dll
It could be great if someone can also try using 32 and 64 bit to see if its the problem.

**Comment by yyr57695** [comment]
Steam Support hasn't gotten back to me yet.  They're usually pretty quick to respond--and have been very helpful each time I've asked a question--so I take this to mean they're looking into it.  I'll update once they've replied.

**Comment by SergioDelValle** [comment]
I wrote to steampublish@valvesoftware.com last week but I had no response... Let's hope they hear you

**Comment by yyr57695** [comment]
Just leaving a note here to let folks know that I did get a response from Steam and they are looking into it.

**Comment by SergioDelValle** [comment]
Wow, thanks a lot, let's hope we get an answer :)

**Comment by SergioDelValle** [comment]
yyr77695 you are an unsung hero, thanks a lot for your efforts :)

**Comment by yyr57695** [comment]
OK, a new wrinkle.
Running the 32-bit build normally results in "lb.isError" being true.
But I tried sticking a breakpoint where my leaderboard requests begin, then pressing "Step Into" repeatedly until everything happened.
All the Steam requests were sent correctly, all of the callbacks were received correctly, and...lo and behold, the leaderboard request actually works.  Same code, same Steam API, the only difference being running at 100% speed versus waiting in between each line's execution.
I'm starting to think that we need Facepunch to weigh in here, but I'll update my Steam Support ticket and see what they say about it.

**Comment by SergioDelValle** [comment]
Maybe steam put some kind of "anti-spam" system to avoid hammering the servers with fast request? I definetly think that Facepunch should check it out because it's becoming clear that it's a problem either in it's side or steam's.

**Comment by yyr57695** [comment]
OK, we have a workaround.  Immediately following any leaderboard request with

Thread.Sleep(200);

causes it to work in 32-bit mode.  It just also causes an annoying stutter.  Values less than 200 sometimes don't work (I tried 150).

Next I'm going to see if I can add it to the Facepunch.Steamworks source code instead, to avoid the stutter in my game.

As to the root cause, that's beyond my feeble mind.  We may have to wait until such time that someone at Facepunch (or just someone who knows what they're doing more than I do) actually finds this and takes a look.

**Comment by SergioDelValle** [comment]
Is there any news?

I've been trying several things on my end, including the aforementioned sleep.

I try to get the leaderboard with:
board = Client.Instance.GetLeaderboard("Ranking", Client.LeaderboardSortMethod.Descending, Client.LeaderboardDisplayType.Numeric);
Then sleep for up to a full second but I always get board.isError

Here's the full code i'm testing. Works OK in Unity, fails as 32bit stand-alone... and I believe is the most basic way to connect to the leaderboard. Am I missing something?

```
using UnityEngine;
using Facepunch.Steamworks;
using System.Linq;
using Facepunch.Steamworks.Callbacks;
using System.Threading;
using System.Collections;

public class SteamController : MonoBehaviour
{

    public bool initialized = false;

    [Header("Steam Data")]
    public ulong steamId;
    public string username;
    public int friendCount;
    public Texture2D userAvatar;

    public enum DataStatus { NotLoaded, Asking, Ok, Offline };
    public DataStatus basicUserStatus = DataStatus.NotLoaded;

    Leaderboard board = null;

    internal void Initialize()
    {
        //Detect platform
        Facepunch.Steamworks.Config.ForUnity(Application.platform.ToString());

        //Create the client for the game
        new Facepunch.Steamworks.Client(XXXXXX);

        // Make sure we started up okay
        if (Client.Instance == null)
        {
            Debug.LogError("Error starting Steam!");
            basicUserStatus = DataStatus.Offline;
            return;
        }

        // Print out some basic information
        steamId = Client.Instance.SteamId;
        username = Client.Instance.Username;
        friendCount = Client.Instance.Friends.AllFriends.Count();

        initialized = true;
        basicUserStatus = DataStatus.Ok;        
    }


    internal void CloseConnection()
    {
        if (Client.Instance != null)
        {
            // Properly get rid of the client if this object is destroyed
            Debug.Log("Closing Steam");
            Client.Instance.Dispose();
            if (Client.Instance == null)
            {
                Debug.Log("Steam closed");
            }
            else
            {
                Debug.LogWarning("Steam still active!");
            }
        }
    }


    // Update is called once per frame
    void Update()
    {
        if (!initialized) return;
        if (Client.Instance == null) return;

        // This needs to be called in Update for the library to properly function
        Client.Instance.Update();
        
        if (Input.GetKeyDown(KeyCode.E))
        {
            StartCoroutine(TestGetLeaderboard());
        }
    }


    IEnumerator TestGetLeaderboard()
    {
        Debug.Log("Testing Ranking");
        board = Client.Instance.GetLeaderboard("Ranking", Client.LeaderboardSortMethod.Descending, Client.LeaderboardDisplayType.Numeric);
        yield return new WaitForSeconds(1);
        Debug.Log("Is valid: " + board.IsValid + " - Is error: " + board.IsError + " - Is Querying: " + board.IsQuerying);
    }
}
```

**Comment by yyr57695** [comment]
Sorry for the late reply, have not had much time to devote to projects lately.
The way my game does it, after setting up the Steam client as steamClient, is:
1) Game calls a method named SubmitTimeToLeaderboards
2) SubmitTimeToLeaderboards contains a call to steamClient.GetLeaderboard, which executes as follows:
```
                    lb = steamClient.GetLeaderboard(leaderboardNames[whichLeaderboard], Client.LeaderboardSortMethod.Descending,
                        Client.LeaderboardDisplayType.TimeMilliSeconds);
```

3) SubmitTimeToLeaderboards next executes this:
```
                if (!Environment.Is64BitProcess)
                    Thread.Sleep(225);
```
(I believe this is Using System.Threading)

4) Finally, SubmitTimeToLeaderboards sets a bool to True, letting the game know that a query is in progress.  That completes its work.

5) On the next frame, the game sees that a query is still in progress, then calls a second method called SubmitTimeToLeaderboardsContinue.  The first thing it does is:
`                if ((lb.IsValid) || (lb.IsError))
`
If this returns false, nothing else happens until the next frame.  If it returns true, lb.AddScore is called.

Currently, in 32-bit builds, this worked for me on release, then didn't work, then worked once again after I added step 3 above.  Hopefully this helps?

I will say this: after 3 months with no replies from Facepunch, I now plan to re-implement my game's Steam support using Steamworks.NET instead, when I find the time to do it.  I've already sunk many hours into this issue that I'd really wanted to use for further game development.  It's a shame, because Facepunch.Steamworks seemed really easy to use at first, but if we keep seeing issues like this, and it's not going to be supported, then it's going to cost me more time in the long run than it saves =(

**Comment by Haapavuo** [comment]
@yyr57695 Same here. Facepunch is buggy. client.GetLeaderboard throws a null exception. Unusable.

**Comment by elzner2** [comment]
I had a similar problem connecting to my Leaderboards, IsError was set when first connecting. I found out that after a few retries the error always disappeared.

This is the original routine from the Facepunch Test Project:
```
var board = client.GetLeaderboard( "TestLeaderboard", Steamworks.Client.LeaderboardSortMethod.Ascending, Steamworks.Client.LeaderboardDisplayType.Numeric );

var time = Stopwatch.StartNew();
while ( !board.IsValid )
{
    Thread.Sleep( 10 );
    client.Update();

    if (time.Elapsed.TotalSeconds > 10 )
    {
        throw new Exception("board.IsValid took too long");
    }
}
```

I changed it to include a few retries and an additional sleep():
```
var board = client.GetLeaderboard( "TestLeaderboard", Steamworks.Client.LeaderboardSortMethod.Ascending, Steamworks.Client.LeaderboardDisplayType.Numeric );

int retries = 0;
bool quit = false;
var time = Stopwatch.StartNew();
while ( !board.IsValid && !quit)
{
    Thread.Sleep( 10 );
    client.Update();

    if (board.IsError)
    {
        if (retries < 5)
        {
            retries++;
            board = client.GetLeaderboard( "TestLeaderboard", Steamworks.Client.LeaderboardSortMethod.Ascending, Steamworks.Client.LeaderboardDisplayType.Numeric );
            Thread.Sleep(100);
        }
        else
        {
            quit = true;
        }
    }
	
    if (time.Elapsed.TotalSeconds > 10 )
    {
        quit = true;
    }
}
```

so far this has helped as a workaround...

**Comment by elzner2** [comment]
I tested with older versions of the steam_api.dll - same result
current dll version (sdk 1.42) is 4.28.51.7
sdk 1.41 has version 4.4.91.85
sdk 1.40 has version 3.92.72.58

I'm experiencing the same error with all versions

**Comment by Lehha95** [comment]
Same problem. 
For some players the leaderboard returns IsError. 64 Bit Builds work well for these users.

**Comment by yyr57695** [comment]
Since the last time I posted, I completely re-implemented the Steam support in my game using Steamworks.NET instead.  It took many hours to do this, but the advertised features in my game now once again work perfectly.
I assumed that doing this would cause Facepunch to fix their library's errors, in the same way that buying a new umbrella is the fastest way to find the one you misplaced.  But I now see that unfortunately, nothing has changed.
So, for the benefit of others trapped in this situation, I documented my code and am offering it here:
http://hiaaron.com/?q=code
Hopefully this is a help to someone.
