### ISSUE TITLE
Is the development stopped?

### ISSUE THREAD

**Issue by nidaynere** [Facepunch/Facepunch.Steamworks#173]
We are experiencing performance issues with Voice and RemoteStorage at Unity 2018.
I like to know if the development is stopped or not.
So we can move to Steamworks.Net

**Comment by V-ZINC** [comment]
Why would development have stopped. Facepunch uses this for themselves as well and look at the last commit. it may have been a couple of months ago, but there is not much to update. And if there is issues well their probably fixing it or its your code.

**Comment by nidaynere** [comment]
Yes I though it so I tried it on an empty project with single line of code.
Client.Instance.Voice.WantsToRecording = true

**Comment by yyr57695** [comment]
V-ZINC, please consider this:
The last reply posted here in Issues by a Facepunch developer was in early March.
Since then, over 20 new issues have been opened--some of them affecting the advertised features in already-released games--and not only has there been no support, there has not even been any sort of acknowledgement.
On one hand, it's not like Facepunch have broken a commitment or violated a support contract, and I know that we all get busy.  But total radio silence for over 3 months leads me to believe that either the project has been abandoned, or that it's a low enough priority for them that I should treat it as such.  So at this point, I plan to try re-implementing the Steam support in my game, using the actively-supported Steamworks.NET instead--unless things change before I find the time to do this.

**Comment by V-ZINC** [comment]
ok well, we can see Garry is the only one from facepunch working on this and some others from the public. I do understand what you are saying, he may not reply to issues or even have added anything new. If you read one of his blogs he talks about how he is taking a break from making reusable code and rust and other things to just make a game. A game that looks pretty good btw Garry ;). Now that also uses facepunch.steamworks. If he sees that it has everything it needs for his game he probs wont add anything during his "break". Some of the issues (Which i haven't looked at) are probably issues already solved, not closed by the person, answered on Garry's blog. Also facepunch.steamworks is easier to use in my opinion. steamworks.net just chucks you in and says go translate c++ into c# buds. I genuinely want to know your opinion thx

**Comment by yyr57695** [comment]
Yes, Facepunch.Steamworks is much easier to use.  I know this because I'm in the process of implementing Steamworks.Net right now.  But since Steamworks.Net maps 1:1 with the Steamworks SDK, there is no layer in between your game and Steam.  So once I'm able to get this up and running, everything should work fine, and if I need help, I can contact Steam Support directly.

The issues many of us are now experiencing do not seem to be Steam's fault, nor are we implementing Facepunch.Steamworks incorrectly.  So something is happening in between.  I personally don't understand the innerworkings well enough to fix the problems occurring in this "in between" layer, so I must rely on support instead.  If support is not present, it defeats the purpose of using the library in the first place.

Again, I have nothing against the devs, and they can support this or not; it's up to them entirely.  And I understand how much effort it takes to complete a project, so if they want to work on their own projects, I absolutely respect that.  But my game released in February, and the leaderboards haven't been working 100% since April.  This is an advertised feature of my game, so I'm required to support it.  To that end, I must do what I have to do.

**Comment by V-ZINC** [comment]
Ay boys they just made a commit hazza !! @yyr57695  @nidaynere
