### ISSUE TITLE
Client.Instance null if no internet

### ISSUE THREAD

**Issue by LoneDev6** [Facepunch/Facepunch.Steamworks#174]
Hello,
if I call Client.Instance when no internet is available but Steam is opened I get a null result.
Is there a way to init the Client when no internet is available?

Thanks

**Comment by V-ZINC** [comment]
have a look on the google machine about steam multiplayer with steamworks. it may not be facepunch but it should be easy to translate.

**Comment by LoneDev6** [comment]
mh, ok

**Comment by LoneDev6** [comment]
anyone else?

**Comment by igniuss** [comment]
That's because [this call](https://github.com/Facepunch/Facepunch.Steamworks/blob/1ccea72a13230fa435b73e9e949ff457d05ff63f/Facepunch.Steamworks/Interop/Native.cs#L65) returns false when the client doesn't have an **active** connection to steam. You can find more details on the [Steamworks SDK pages](https://partner.steamgames.com/doc/api/ISteamUser#BLoggedOn)

**Comment by LoneDev6** [comment]
Thanks!
So it's normal that I can't know the name of the user if he has no internet connection or if he had set steam to offline mode?

**Comment by igniuss** [comment]
Basically, you'll might be able to fetch username, but not with the default facepunch interface. 
You can always change the SDK to accommodate for this feature if the Steamworks SDK does allow this functionality though.

**Comment by LoneDev6** [comment]
I see...
Did you ever had that problem on developement?

**Comment by igniuss** [comment]
In my past projects, I only needed username when playing online, and if steamworks fails I just disable multiplayer entirely. 
Since it means they either launched offline, or without steam.

I do have a coroutine running that tries to reconnect to steam every 10 or so minutes, and when you try to look for servers, if the instance is nil. Works well enough for my purposes.

**Comment by LoneDev6** [comment]
I see... nice :)

**Comment by clansfear** [comment]
After encountering the same issue I believe the ` if ( !user.BLoggedOn() )` of _InitClient_ should be omitted altogether. Referring to the [official documentation](https://partner.steamgames.com/doc/api/ISteamUser#BLoggedOn) all API calls will perform the check anyway if required, and currently you lose all steam functionality when the Internet connection is down. 

At the same time call to the BLoggedOn could be exposed in the wrapper, as it may come in handy (for instance to disable trying to create multiplayer sessions as long as you're not logged in / offline).

**Comment by LoneDev6** [comment]
Good to see someone else that noticed that important issue.
Sure! I think that would help since I hate to code hacks to make other libs work and I want to keep the code as clean as possible
