### ISSUE TITLE
Couldn't initialize Steam

### ISSUE THREAD

**Issue by SurDno** [Facepunch/Facepunch.Steamworks#185]
UnityEngine.Debug:LogWarning(Object)
SteamClient:Start() (at Assets/Plugins/Facepunch.Steamworks/Utility/SteamClient.cs:54)

Steam is launched, native dlls are in root. I use 480 steam app id in both SteamClient.cs and steam_appid.txt.

**Comment by dylanh724** [comment]
How did you figure this out? Oddly enough, I can get it working in the editor on my main project -- but I get this error on a test vanilla project! Lol!

**Comment by SurDno** [comment]
I still have not.

**Comment by SurDno** [comment]
@dylanh724, I am back to Facepunch.Steamworks. Just got approved with my tax info and got my app id. I thought that it could fix the problem, but that made no difference, I still get this error on both my main project and demo one. 
Have you figured this out?

**Comment by SurDno** [comment]
![image](https://user-images.githubusercontent.com/35204405/47742955-dc0b6080-dc8e-11e8-9454-a83dbfa0f5d9.png)
Native dlls are in the root folder of my project, steam app_id is set to 420, Steam is open in the background. Client.isValid always returns false, Steam does not show that I play Spacewar, Unity never gets my Steam avatar.
@garrynewman, any ideas? I am completely clueless.

**Comment by SurDno** [comment]
That has not been fixed.

**Comment by Jedimaster4559** [comment]
I just had this issue with my game, and I found it very helpful to check the following checklist as per steam's documentation:

>  - The Steam client isn't running. A running Steam client is required to provide implementations of the various Steamworks interfaces.
>  - The Steam client couldn't determine the App ID of game. If you're running your application from the executable or debugger directly then you must have a steam_appid.txt in your game directory next to the executable, with your app ID in it and nothing else. Steam will look for this file in the current working directory. If you are running your executable from a different directory you may need to relocate the steam_appid.txt file. (Note: This doesn't apply to Facepunch.Steamworks since you set this with the .Init command)
>  - Your application is not running under the same OS user context as the Steam client, such as a different user or administration access level.
>  - Ensure that you own a license for the App ID on the currently active Steam account. Your game must show up in your Steam library.
>  - Your App ID is not completely set up, i.e. in Release State: Unavailable, or it's missing default packages.

These may prove helpful if any of you happen to come across this issue again like I did. You might also find some more helpful information about this here: [https://partner.steamgames.com/doc/sdk/api#initialization_and_shutdown](https://partner.steamgames.com/doc/sdk/api#initialization_and_shutdown)

For me, the issue was that the app id was not setup correctly, and hence I couldn't run the application. If you are running the game in an unreleased state, only people who have been marked as developers through your steam partner account will be able to successfully complete initialization. Testing with 480 (Spacewar AppID) typically is a good resolution to this problem.
