### ISSUE TITLE
Expose IsOverlayEnabled

### ISSUE THREAD

**Issue by BonneCW** [Facepunch/Facepunch.Steamworks#198]
Hey there,

I would like to pause my game while IsOverlayEnabled is true, but I can't find the method being exposed. Would it be possible to add this in a next update or is it already possible somehow and I just don't see it?

**Comment by clansfear** [comment]
For a quick and ugly workaround you can expose GameOverlayActivated_t struct of SteamNative.Structs, and get it through subscribing to OnAnyCallback (and detected when its argument is GameOverlayActivated_t).

It appears you can only detect state changes, and can't just get current state, but I may look into that next week, and create a Pull Request with some form of the feature,.

**Comment by clansfear** [comment]
I believe it isn't exposed right now, though enabling it should be easy.
You could create a public property in _Overlay_ or _Client_ class that refers to the SteamNative.SteamUtils, and calls its IsOverlayEnabled.

I could make a pull request with the feature next week if you want.

**Comment by BonneCW** [comment]
That would be awesome. It doesn't hurry, it's just a thing Valve recommended to do :) So next week is totally fine ;)

**Comment by clansfear** [comment]
So I have forgotten that I already did that once, and current version of Facepunch Steamworks even has that property exposed, but it does something different that one could think - it returns an information whether the overlay has initialized successfully, and is available to the user (though not necessarily 'opened' at a given time).

Steamworks dev forum is quite vague on that topic, and I don't know if there is a clean way to achieve what you want.  I made it work listening for the GameOverlayActivated event, as I wrote in the previous post. If you need details, please write to me.

**Comment by Lockrdr** [comment]
Hey @clansfear could you explain how to subscribe to the OnAnyCallback. I can't seem to find any reference to it. Thanks!

**Comment by clansfear** [comment]
[This example](https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/9b89abd90265af14cf893b1a1bb5377044bec251/Assets/Scripts/SteamTest.cs#L25) shows general case of using OnAnyCallback.

You could then (instead of DebugPrintSteamCallback) wire up something like

```
private void OverlayActivationListener(object obj)
    {
        if (obj is GameOverlayActivated_t)
        {
            OverlayShowing = ((GameOverlayActivated_t)obj).Active == 1;
        }
}
```

Where OverlayShowing is a bool member of a class.
You won't be able to get to the _GameOverlayActivated_t_ type unless you find it, and make it public in Facepunch.Steamworks source (and recompile library). As a last resort, if you don't want to do this, and you're performing the check when performance is non-issue, you could reflect the name, and equal to the string (like in [that](https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/9b89abd90265af14cf893b1a1bb5377044bec251/Assets/Scripts/SteamTest.cs#L68) testing method), however I don't recommend that.

This is quite a dirty way of doing this, but it gets the job done for me, and right now I haven't found a better way. I would glady listen if someone had something better.

**Comment by igniuss** [comment]
In case you haven't found the answer yet, `Overlay` has a public bool `Enabled`, this returns `IsOverlayEnabled()` on the native side.

There's also a bool `IsOpen`, which gets set by a callback. You can see the implementation [here.](https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/Client/Overlay.cs#L18) (not sure why there's two implementations, but ya'know)

**Comment by clansfear** [comment]
What do you mean by two implementations? `IsOverlayEnabled()` doesn't actually tell you if the overlay is opened (and you're seeing it) it merely informs you whether it has initialized & is possible to access (in particular it may be inaccessible for the first few seconds after starting your game)

Thank you @Rohansi for the concise `IsOpen` implementation

**Comment by igniuss** [comment]
Oh woops, yeah that's an error on my end, somehow didn't realize that when I was typing that out :sweat_smile:

**Comment by sqrMin1** [comment]
I was in the same situation and just wanted to post the solution here, because I found this issue first.

Subscribe to: `SteamFriends.OnGameOverlayActivated`
