### ISSUE TITLE
Facepunch.Steamworks.dll is not present on GitHub (just the .meta file)

### ISSUE THREAD

**Issue by Carniphage** [Facepunch/Facepunch.Steamworks#287]
Am I being dumb?  I can see the .meta file, but the .dll itself appears to be not there.

**Comment by Agoxandr** [comment]
https://github.com/Facepunch/Facepunch.Steamworks/blob/master/.gitignore

Yes you are being very ignorant, because it's supposed to be like this. The file is in the gitignore. You are supposed to build it yourself. Make sure you build as release. If it would be included in the git you would always commit changes that are not relevant to source code. This is not an issue.

**Comment by Carniphage** [comment]
Thanks for the response. 

Turns out that the file I need is obtained by clicking the little releases tab-button, and downloading the release bundle. 

So in this specific instance, there is absolutely no requirement to build the dll myself.
