### ISSUE TITLE
Throwing inside a Callback breaks all further Callbacks

### ISSUE THREAD

**Issue by LukasKastern** [Facepunch/Facepunch.Steamworks#301]
I've noticed that if you throw inside a Callback no further Callbacks will be called.
The OnCallbackException which catches all Callback Exceptions made it way harder for me to debug the cause of them not working.
Since i had no idea of it's existence and therefor i didn't get any errors. 
I'm not sure if this should be made more obvious or completely removed.

**Comment by garrynewman** [comment]
IIRC OnCallbackException is there because if you throw in an async call you don't actually know it's been handled. This provides a way for implementations in Unity to always print the exception out.

Would rethrowing in a OnCallbackException implementation work? Or do we need to do it in our code?

**Comment by LukasKastern** [comment]
That's how i have set it up right now, by just throwing the exception that i would get from the OnCallbackException. I still have no idea why all further callbacks break when you throw inside a callback.

**Comment by garrynewman** [comment]
So what it is, is that we have the RunCallbacks stuff running async automatically, so you don't actually need to call it in your game loop. This means that you can block and wait for Async stuff on your game loop and the callbacks will still run as you'd expect.

The issue is that if something happens in those callbacks, it's unhandled. So that's why OnCallbackException exists.

The mistake in this case was that if you're calling RunCallbacks manually it's still wrapped in a try catch, which isn't really what you want.

So I've just undone that behaviour. Calling RunCallbacks manually will throw an exception as usual.

I've also added an optional argument to Client/Server.Init functions that allow you to prevent the AsyncCallbacks shit.

**Comment by LukasKastern** [comment]
Oh i didn't even know that the RunCallbacks thing worked like this, i ported my game from Steamworks.Net where you had to call it manually. Thanks a lot!
