### ISSUE TITLE
Steamworks.Ugc.Item.Owner.Name returning unknown

### ISSUE THREAD

**Issue by bobandfriends** [Facepunch/Facepunch.Steamworks#464]
- OS: [e.g. iOS] Windows 10 version 
- Using Facepunch.Steamworks.win32 version 2.3.3 (nuget pkg)

When querying workshop items, Steamworks.Ugc.Item.Owner is returning "Unknown" for the name unless the user that uploaded the workshop content is the currently logged in user (you) or a user on your friends list. Is there a way to query the author of a Workshop item from random users or is the unknown result intended behavior? 
```

**Comment by Arugin** [comment]
Hello. I am getting [unknown] too

**Comment by Arugin** [comment]
Got it, You need to call `item.Owner.RequestInfoAsync()` to get a name.
I think this issue can be closed.

**Comment by MarshMello0** [comment]
I'be been using this RequestInfoAsync/SteamFriends.RequestUserInformation fine on Windows. Then recently built my program for Linux64 and it seems never to download the username. I either get `[unknown]` `anonymous` or an empty string.

I am testing on a VM running Ubuntu 25.10 and installed Steam through the package manager by Canonical. My program builds Facepunch.Steamworks from source instead of referencing it from NuGet.
