### ISSUE TITLE
Using without Steam & Unity

### ISSUE THREAD

**Issue by TheRealLenon** [Facepunch/Facepunch.Steamworks#573]
Does this C# binding include the use without Steam and Unity?

**Comment by Rohansi** [comment]
This does work outside of Unity.

Not sure how you'd run this without Steam since the entire purpose is to integrate with Steam.

**Comment by sqrMin1** [comment]
You can use it outside without any problems.

Just do:

- initialize with `SteamClient.Init(AppID);`
- run callbacks with `SteamClient.RunCallbacks();`
- close with `SteamClient.Shutdown();`

If you don't have a game- or updateloop available you can just run the callbacks with a timer or doing it manually for example. In some cases you don't even need to run the callbacks. It depends on what you want to achieve.

However you need to have the steam client installed to receive data. Otherwise you would need to use the SteamWebApi to eliminate the steam client dependency.
