### ISSUE TITLE
EntryPointNotFoundException: Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL

### ISSUE THREAD

**Issue by SegerEnd** [Facepunch/Facepunch.Steamworks#657]
**Describe the bug**
Unable to find an entry point named: SteamAPI_SteamInput_v001.
When i run/debug the game i see the steam overlay using ctrl + tab but i get an error in the console.

**Error in console:**
Setting breakpad minidump AppID = 480
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198389420911 [API loaded no]
System.EntryPointNotFoundException: Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL 'steam_api64'.
   at Steamworks.ISteamInput.SteamAPI_SteamInput_v001()
   at Steamworks.ISteamInput.GetUserInterfacePointer()
   at Steamworks.SteamInterface.SetupInterface(Boolean gameServer)
   at Steamworks.ISteamInput..ctor(Boolean IsGameServer)
   at Steamworks.SteamInput.InitializeInterface(Boolean server)
   at Steamworks.SteamClient.AddInterface&#91;T]()
   at Steamworks.SteamClient.Init(UInt32 appid, Boolean asyncCallbacks)
   at PlaceholderName.MainGame.Initialize() in C:\Users\Gebruiker\PlaceholderName\MainGame.cs:line 22

**To Reproduce**
Install Facepunch.Steamworks 2.2.4 package with NuGet
Add steam_api64.dll in project folder set Copy To oTutput Directory to Copy always or copy if newer.
paste Steamworks.SteamClient.Init(appID, false); in Initialize() method.

**Calling Code**
```
try
{
   Steamworks.SteamClient.Init(480, false); //bool asyncCallbacks true gives same error
}
catch (System.Exception e)
{
   System.Console.WriteLine(e);
}
```

**Expected behavior**
I expect no exceptions in the console

**Desktop:**
Windows 10, [Monogame v3.8.0.1641](https://www.nuget.org/packages/MonoGame.Framework.DesktopGL/3.8.0.1641?_src=template), [Facepunch.Steamworks NuGet v2.3.3
](https://www.nuget.org/packages/Facepunch.Steamworks/2.3.3?_src=template)

**Additional context**
I tried multiple different steam_api64.dll files from this repository and from the offical steamworks site.

**Comment by ess4654** [comment]
I am having this exact same problem

**Comment by kkukshtel** [comment]
Running into this as well - notably this is from a build off the main branch. NuGet is fine.

**Comment by ess4654** [comment]
I found the solution to this issue. The problem is that at some point Steam updated their DLL plugin and Facepunch has not accounted for the new steam_api.dll integration. If you download the latest 07 version of the DLL it will not work. I found that it did work however on version 05.69.73.89 of both steam_api.dll (32 bit) and steam_api64.dll (64 bit) 

To find the version of the DLL you can use the below command in Windows Power Shell.
(Get-Command <path to steam_api.dll>).FileVersionInfo.FileVersion

It will tell you what version of the API you have and if you replace it with the correct one then Steam will initialize again.

**Comment by GordiNoki** [comment]
@ess4654 Thanks! If anyone needs it, version 05.69.73.89 is version 1.48 of the sdk.
