### ISSUE TITLE
Reading Binary files on Osx does not return same array as on Windows.

### ISSUE THREAD

**Issue by MWc0c0** [Facepunch/Facepunch.Steamworks#69]
Windows
Client.Instance.RemoteStorage.ReadBytes("save.dat");
Result: 0,1,0,0,0,255,255,255,255,1,0,0,0 etc

Osx
Client.Instance.RemoteStorage.ReadBytes("save.dat");
Result: 13,170,135,121,34,10,123,10,9,34,10 etc

Any idea why the result would be different? I copied over the exact same file, and when I try to read the file directly from C# (File.ReadAllBytes()), it returns the correct array on both Windows and Osx.

**Comment by GroundCombo** [comment]
I bumped into the same issue while trying out the plugin, and this is most likely related to issue #77. NormalizePath() should not have the .SubString(3) for the non-Windows version. Unfortunately I wasn't able to verify this because I can't figure out how to build this dll on Mac in a Unity-compatible way.

**Comment by GMR516** [comment]
Is this fixed now? This issue was a long time ago.

**Comment by GroundCombo** [comment]
I tested this with the Unity asset store package, but just now I noticed that the store version is dated Jul 07, sooo... it might be fixed. Is there a more recent binary package somewhere, or instructions on what I need to build it on a Mac?

**Comment by GroundCombo** [comment]
I managed to build the dll from master and it is indeed fixed, reading and writing works for me.
