### ISSUE TITLE
Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL 'steam_api64

### ISSUE THREAD

**Issue by QTPah** [Facepunch/Facepunch.Steamworks#699]
I am using the NuGet Facepunch package without unity. When i try to initiate a client with `SteamClient.Init(x)` my comiler didn't seem to find `steam_api64`. When i added it to `.nuget\packages\facepunch.steamworks.dll\1.53.0\lib` i get the following error:
`System.EntryPointNotFoundException: 'Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL 'steam_api64'.'
`

i tried to replace the dll with the same released under `Facepunch.Steamworks.2.3.2\Unity\redistributable_bin\win64` but the same error pops up.

**Comment by hlpdev** [comment]
Having the same issue. Can't seem to figure out what's causing it

**Comment by ZhangHuan0407** [comment]
I'm using unity packaging.
At first, it was a failure to package to MacOS, and then I blindly changed the bundle under OSX... 
I'm having this issue as well.

I used this person's package, and after replacing the folder, I manually corrected the configuration of the .meta file, and then exported to macOS normally. At least calling init and RestartAppIfNecessary doesn't give an error.

https://github.com/Facepunch/Facepunch.Steamworks/issues/591#issuecomment-1478735946

I confirm that the release version of facepunch has an issue on M2.(2024/1/17)
Try this unofficial version?

**Comment by realcoloride** [comment]
Hello and sorry for the necro. This is caused because Facepunch.Steamworks uses an older version of the SteamworksSDK causing the bindings to be incorrect if you use a more recent version of Facepunch.Steamworks. 

After manually testing a lot of steam SDK versions, I found that the version `1.48a` seems to go correctly with the bindings.
[(Click here to download it)](https://partner.steamgames.com/downloads/steamworks_sdk_148a.zip)
![image](https://github.com/Facepunch/Facepunch.Steamworks/assets/108619637/b610f391-1974-48fe-88cc-6d99dc8afc7d)

**Comment by MisledUtopia** [comment]
holy cow you are a life saver... this has been so frustrating
